name: casino
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_storage: ^2.0.3
  http: ^0.13.4
  get: ^4.6.1
  firebase_messaging: ^11.2.5
  flutter_local_notifications: ^9.2.0
  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6

  geolocator: ^8.0.3
  image_picker: ^0.8.4+4
  flutter_facebook_auth: ^4.0.1
  flutter_secure_storage: ^5.0.2
  percent_indicator: ^4.0.0
  flutter_rating_bar: ^4.0.0
  sliding_sheet: ^0.5.2
  google_maps_flutter: ^2.1.1
  #flutter_staggered_grid_view: ^0.4.1
  location: ^4.3.0
  dio: ^4.0.4
  http_parser: ^4.0.0
  carousel_slider: ^4.0.0
  intl: ^0.17.0
  flutter_stripe: ^2.1.1
  flutter_image_compress: ^1.1.0
  sign_in_with_apple: ^3.3.0
  firebase_auth: ^3.3.5
  geocoding: ^2.0.2
  url_launcher: ^6.0.17
  dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/logo.png
    - assets/images/location.png
    - assets/images/english_lang.png
    - assets/images/spain_flag.png
    - assets/images/resend.png
    - assets/images/profilePic.png
    - assets/images/apple.png
    - assets/images/facebook.png
    - assets/images/casion_table_report.png
    - assets/images/profile_adds.png
    - assets/images/profile_review_dummy.png
    - assets/images/community_casion.png
    - assets/images/share.png
    - assets/images/noun_comment.png
    - assets/images/likes.png
    - assets/images/thumbs_up.png
    - assets/images/covid.png
    - assets/map_styles/dark.json
    - assets/images/blackjack.png
    - assets/images/roulette.png
    - assets/images/poker.png
    - assets/images/game_card.png
    - assets/images/game.png
    - assets/images/card_reward.png
    - assets/images/bed.png
    - assets/images/food.png
    - assets/images/noun_casino.png
    - assets/images/add_profile.png
    - assets/images/drop_down.png
    - assets/images/splace_background.jpeg
    - assets/images/filter.png
    - assets/images/heart.png
    - assets/images/casion_reports.png
    - assets/languages/
